//! The `completions` command: emit a static shell-completion script generated
//! from the live final `Cli` (CMP-01). The last v2.0 meta-command, planned
//! DEAD-LAST so the emitted script captures EVERY flag added in Phases 6-10.
//!
//! Flow (Pattern 1 — thin orchestrator over `clap_complete`):
//! `run()` first prints an INERT `#`-comment registration header (D-10, the first
//! inert place) then hands `crate::cli::Cli::command()` — the live, final argument
//! tree — to [`clap_complete::generate`], which writes the completion script to
//! stdout ONLY. No manual flag enumeration: [`clap::CommandFactory`] reflects every
//! subcommand + global flag automatically, so the script can never drift from the
//! real CLI (SC3 — the script references `config`/`completions` and the global
//! `--json`/`--clip`/`--no-color` flags plus the Phase-8/9/10 depth flags).
//!
//! Output purity (D-10, mirrors `--json`): stdout carries EXACTLY the inert header
//! and the generated script — no per-run stderr chatter (it would fire even under
//! redirection), no ANSI, no BOM — so `box completions powershell > _box.ps1` and
//! piping into `$PROFILE` stay uncontaminated.
//!
//! # Spine note
//! `completions` still flows through `init_config`/`init_output` harmlessly, but its
//! real input is `Cli::command()`. It does NOT emit a `--json` document (its output
//! IS a script); the global flags parse but produce no JSON (SC4 parse-but-ignore).

use clap::{Args, CommandFactory};
use clap_complete::Shell;

use crate::commands::RunCommand;

/// The PowerShell registration one-liner (D-10). It lives in TWO inert places: the
/// generated script's `#`-comment header (written by [`write_header`]) AND this
/// subcommand's `long_about` (the multi-paragraph doc-comment on the `Completions`
/// variant in `cli.rs`), so the recipe is self-documenting from BOTH `box
/// completions powershell --help` AND a redirected script file. `install.ps1
/// -RegisterCompletions` registers this SAME live-command form.
pub const PS_REGISTER_ONELINER: &str = "box completions powershell | Out-String | Invoke-Expression";

/// `box completions <shell>` — generate a shell-completion script (CMP-01 / D-09,
/// the rustup pattern). The required positional [`Shell`] is a `clap_complete`
/// `ValueEnum` (bash|zsh|fish|powershell|elvish), so a bad value is a clap exit-2
/// usage error and `--help` lists the shells for free — no local enum needed.
#[derive(Debug, Args)]
pub struct CompletionsArgs {
    /// Shell to generate a completion script for (bash, zsh, fish, powershell, elvish).
    #[arg(value_enum)]
    pub shell: Shell,
}

impl RunCommand for CompletionsArgs {
    fn run(self) -> anyhow::Result<()> {
        let mut stdout = std::io::stdout();

        // D-10 (first inert place): an INERT `#`-comment registration header BEFORE
        // the script. A `#` comment is inert in bash/zsh/fish/powershell/elvish, so
        // the artifact still executes AND self-documents its registration even after
        // redirection to a file. PowerShell names the exact one-liner to add to
        // $PROFILE; the other shells get a generic provenance line.
        write_header(self.shell, &mut stdout)?;

        // Generate against the LIVE final Cli (SC3): `CommandFactory` hands the
        // complete argument tree — every subcommand incl. config/completions and the
        // global --json/--clip/--no-color flags — so the script auto-reflects every
        // Phase-6..10 flag with no manual enumeration. stdout ONLY (D-10 purity).
        clap_complete::generate(
            self.shell,
            &mut crate::cli::Cli::command(),
            "box",
            &mut stdout,
        );
        Ok(())
    }
}

/// Write the inert `#`-comment registration header (D-10, first inert place).
/// PowerShell gets the two-line recipe naming [`PS_REGISTER_ONELINER`]; every other
/// shell gets a single generic provenance line. All lines are `#`-prefixed → inert
/// in every supported shell, so the emitted script both executes and self-documents.
fn write_header(shell: Shell, buf: &mut impl std::io::Write) -> std::io::Result<()> {
    match shell {
        Shell::PowerShell => {
            writeln!(
                buf,
                "# To enable tab-completion, add this line to your PowerShell $PROFILE:"
            )?;
            writeln!(buf, "#   {PS_REGISTER_ONELINER}")?;
        }
        other => {
            writeln!(buf, "# Generated by box completions {other}")?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The PowerShell header is a two-line `#`-comment block carrying the verbatim
    /// registration one-liner (D-10 first inert place) — locked here so the inert
    /// header can never silently drop the recipe.
    #[test]
    fn powershell_header_is_inert_and_carries_oneliner() {
        let mut buf = Vec::new();
        write_header(Shell::PowerShell, &mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        // Every emitted line is a `#`-comment (inert in PowerShell).
        for line in text.lines() {
            assert!(line.starts_with('#'), "header line must be inert: {line:?}");
        }
        assert!(
            text.contains(PS_REGISTER_ONELINER),
            "the PowerShell header must name the registration one-liner verbatim"
        );
    }

    /// A non-PowerShell shell gets a single inert `#` provenance line naming the
    /// shell (best-effort per D-09), and NEVER the PowerShell recipe.
    #[test]
    fn other_shell_header_is_generic_inert_line() {
        let mut buf = Vec::new();
        write_header(Shell::Bash, &mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.starts_with('#'), "header must be an inert comment");
        assert!(text.contains("bash"), "header should name the shell: {text:?}");
        assert!(
            !text.contains(PS_REGISTER_ONELINER),
            "non-powershell header must not carry the PowerShell recipe"
        );
    }
}
